name: pull request workflow

on: pull_request

env:
  GO_VERSION: '1.21'

jobs:
  # Check if there is any dirty change for go mod tidy
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          stable: 'false'
          go-version: ${{ env.GO_VERSION }}

      - name: lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: ${{ env.GO_VERSION }}

      - name: test
        run: go test -v ./...
